import { DEFAULT_USER_AGENT } from '../constants';
import {
	YoutubeTranscriptNotAvailableError,
	YoutubeTranscriptTooManyRequestError,
	YoutubeTranscriptVideoUnavailableError,
} from '../errors';
import type { TranscriptConfig, YouTubePlayerResponse } from '../types';
import { defaultFetch, retrieveVideoId } from '../utils';
import { fetchApiKey, fetchPlayerResponse } from './youtube-api';

export interface PlayerInspectionResult {
	videoId: string;
	playabilityStatus: string;
	captionTracks: Array<{
		languageCode: string;
		name: string;
		kind: string;
		baseUrl: string;
	}>;
	translationLanguages: Array<{
		languageCode: string;
		languageName: string;
	}>;
	hasAutoGeneratedCaptions: boolean;
	error?: string;
}

export interface PlayerInspectionDebugResult extends PlayerInspectionResult {
	debug: {
		steps: Array<{
			step: string;
			status: 'success' | 'error';
			details: Record<string, unknown>;
		}>;
		watchPageHtml?: {
			size: number;
			hasRecaptcha: boolean;
			apiKeyFound: boolean;
			apiKeySnippet?: string;
			/** Full HTML content (only included if includeRawData option is true) */
			content?: string;
		};
		playerResponse?: {
			size: number;
			playabilityStatus: string;
			hasCaptions: boolean;
			captionTracksCount: number;
			/** Full JSON response (only included if includeRawData option is true) */
			content?: unknown;
		};
	};
}

/**
 * Inspect the YouTube player response for a given video
 * Useful for debugging why captions might not be available
 *
 * @param videoId YouTube video ID
 * @param config Optional transcript config (userAgent, custom fetch functions, etc.)
 * @returns Inspection result with playability status and available captions
 *
 * @example
 * ```typescript
 * const inspection = await inspectPlayerResponse('xoriGNUNF7E');
 * console.log(inspection.captionTracks);
 * ```
 */
export async function inspectPlayerResponse(
	videoId: string,
	config?: TranscriptConfig,
): Promise<PlayerInspectionResult> {
	try {
		const identifier = retrieveVideoId(videoId);
		const apiKey = await fetchApiKey(identifier, config);
		const playerJson = await fetchPlayerResponse(identifier, apiKey, config);

		const playabilityStatus = playerJson.playabilityStatus?.status ?? 'UNKNOWN';

		// Try to get captions from multiple possible locations in the response
		const tracklist =
			playerJson.captions?.playerCaptionsTracklistRenderer ??
			playerJson.playerCaptionsTracklistRenderer;

		const captionTracks = tracklist?.captionTracks ?? [];
		const translationLanguages = tracklist?.translationLanguages ?? [];

		return {
			videoId: identifier,
			playabilityStatus,
			captionTracks: captionTracks.map((track) => ({
				languageCode: track.languageCode ?? 'unknown',
				name:
					track.name?.runs?.[0]?.text ??
					track.name?.simpleText ??
					`[${track.languageCode}]`,
				kind: track.kind ?? 'unknown',
				baseUrl: track.baseUrl ?? '',
			})),
			translationLanguages: translationLanguages.map((lang) => ({
				languageCode: lang.languageCode ?? 'unknown',
				languageName: lang.languageName?.simpleText ?? 'Unknown',
			})),
			hasAutoGeneratedCaptions: captionTracks.some((t) => t.kind === 'asr'),
		};
	} catch (error) {
		return {
			videoId,
			playabilityStatus: 'ERROR',
			captionTracks: [],
			translationLanguages: [],
			hasAutoGeneratedCaptions: false,
			error: error instanceof Error ? error.message : String(error),
		};
	}
}

/**
 * Verbose inspection with detailed debug information
 * Returns raw responses and step-by-step logging for troubleshooting
 *
 * @param videoId YouTube video ID or URL
 * @param config Optional transcript config
 * @param options Optional debug options
 * @param options.includeRawData Include full HTML and JSON responses (useful for manual inspection)
 * @returns Detailed inspection result with debug information
 *
 * @example
 * ```typescript
 * const debug = await inspectPlayerResponseDebug('xoriGNUNF7E');
 * console.log(debug.debug.steps); // See each step
 * console.log(debug.debug.watchPageHtml); // See watch page details
 * console.log(debug.debug.playerResponse); // See player response details
 *
 * // With raw data for manual inspection
 * const debugWithRaw = await inspectPlayerResponseDebug('xoriGNUNF7E', undefined, { includeRawData: true });
 * console.log(debugWithRaw.debug.watchPageHtml?.content); // Full HTML
 * console.log(debugWithRaw.debug.playerResponse?.content); // Full JSON
 * ```
 */
export async function inspectPlayerResponseDebug(
	videoId: string,
	config?: TranscriptConfig,
	options?: { includeRawData?: boolean },
): Promise<PlayerInspectionDebugResult> {
	const steps: Array<{
		step: string;
		status: 'success' | 'error';
		details: Record<string, unknown>;
	}> = [];

	let identifier = videoId;
	let watchPageHtmlInfo: PlayerInspectionDebugResult['debug']['watchPageHtml'];
	let playerResponseInfo: PlayerInspectionDebugResult['debug']['playerResponse'];

	try {
		// Step 1: Extract video ID
		try {
			identifier = retrieveVideoId(videoId);
			steps.push({
				step: 'Extract Video ID',
				status: 'success',
				details: { videoId: identifier },
			});
		} catch (error) {
			steps.push({
				step: 'Extract Video ID',
				status: 'error',
				details: {
					error: error instanceof Error ? error.message : String(error),
				},
			});
			throw error;
		}

		// Step 2: Fetch watch page and extract API key
		let apiKey: string | null = null;
		try {
			const userAgent = config?.userAgent ?? DEFAULT_USER_AGENT;
			const watchUrl = `https://www.youtube.com/watch?v=${identifier}`;

			const watchRes = config?.videoFetch
				? await config.videoFetch({
						url: watchUrl,
						lang: config?.lang,
						userAgent,
					})
				: await defaultFetch({
						url: watchUrl,
						lang: config?.lang,
						userAgent,
					});

			if (!watchRes.ok) {
				throw new YoutubeTranscriptVideoUnavailableError(identifier);
			}

			const watchBody = await watchRes.text();
			const hasRecaptcha = watchBody.includes('class="g-recaptcha"');

			if (hasRecaptcha) {
				throw new YoutubeTranscriptTooManyRequestError();
			}

			const apiKeyMatch =
				watchBody.match(/"INNERTUBE_API_KEY":"([^"]+)"/) ||
				watchBody.match(/INNERTUBE_API_KEY\\":\\"([^\\"]+)\\"/);

			if (!apiKeyMatch) {
				throw new YoutubeTranscriptNotAvailableError(identifier);
			}

			apiKey = apiKeyMatch[1];
			watchPageHtmlInfo = {
				size: watchBody.length,
				hasRecaptcha,
				apiKeyFound: true,
				apiKeySnippet: `${apiKey.slice(0, 20)}...`,
				...(options?.includeRawData && { content: watchBody }),
			};

			steps.push({
				step: 'Fetch Watch Page & Extract API Key',
				status: 'success',
				details: {
					htmlSize: watchBody.length,
					hasRecaptcha,
					apiKeyExtracted: true,
				},
			});
		} catch (error) {
			watchPageHtmlInfo = {
				size: 0,
				hasRecaptcha: false,
				apiKeyFound: false,
			};

			steps.push({
				step: 'Fetch Watch Page & Extract API Key',
				status: 'error',
				details: {
					error: error instanceof Error ? error.message : String(error),
				},
			});
			throw error;
		}

		// Step 3: Fetch player response
		let playerJson: YouTubePlayerResponse;
		try {
			if (!apiKey) {
				throw new Error('API key not found');
			}

			playerJson = await fetchPlayerResponse(identifier, apiKey, config);

			const tracklist =
				playerJson.captions?.playerCaptionsTracklistRenderer ??
				playerJson.playerCaptionsTracklistRenderer;

			playerResponseInfo = {
				size: JSON.stringify(playerJson).length,
				playabilityStatus: playerJson.playabilityStatus?.status ?? 'UNKNOWN',
				hasCaptions: !!tracklist,
				captionTracksCount: tracklist?.captionTracks?.length ?? 0,
				...(options?.includeRawData && { content: playerJson }),
			};

			steps.push({
				step: 'Fetch Player Response',
				status: 'success',
				details: {
					playabilityStatus: playerJson.playabilityStatus?.status,
					captionTracksCount: tracklist?.captionTracks?.length ?? 0,
					responseSize: JSON.stringify(playerJson).length,
				},
			});
		} catch (error) {
			playerResponseInfo = {
				size: 0,
				playabilityStatus: 'ERROR',
				hasCaptions: false,
				captionTracksCount: 0,
			};

			steps.push({
				step: 'Fetch Player Response',
				status: 'error',
				details: {
					error: error instanceof Error ? error.message : String(error),
				},
			});
			throw error;
		}

		// Extract final results
		const playabilityStatus = playerJson.playabilityStatus?.status ?? 'UNKNOWN';
		const tracklist =
			playerJson.captions?.playerCaptionsTracklistRenderer ??
			playerJson.playerCaptionsTracklistRenderer;

		const captionTracks = tracklist?.captionTracks ?? [];
		const translationLanguages = tracklist?.translationLanguages ?? [];

		return {
			videoId: identifier,
			playabilityStatus,
			captionTracks: captionTracks.map((track) => ({
				languageCode: track.languageCode ?? 'unknown',
				name:
					track.name?.runs?.[0]?.text ??
					track.name?.simpleText ??
					`[${track.languageCode}]`,
				kind: track.kind ?? 'unknown',
				baseUrl: track.baseUrl ?? '',
			})),
			translationLanguages: translationLanguages.map((lang) => ({
				languageCode: lang.languageCode ?? 'unknown',
				languageName: lang.languageName?.simpleText ?? 'Unknown',
			})),
			hasAutoGeneratedCaptions: captionTracks.some((t) => t.kind === 'asr'),
			debug: {
				steps,
				watchPageHtml: watchPageHtmlInfo,
				playerResponse: playerResponseInfo,
			},
		};
	} catch (error) {
		return {
			videoId: identifier,
			playabilityStatus: 'ERROR',
			captionTracks: [],
			translationLanguages: [],
			hasAutoGeneratedCaptions: false,
			error: error instanceof Error ? error.message : String(error),
			debug: {
				steps,
				watchPageHtml: watchPageHtmlInfo,
				playerResponse: playerResponseInfo,
			},
		};
	}
}
